In [1]:
import numpy as np
import time


**vectorization** by vectorization the numpyimplements mathematical operation on all the elements simultaneously because it uses SIMD

In [4]:
arr1=[1,2,3,4,5,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4]
start=time.time()
result=[x**2 for x in arr1]
end=time.time()
print(result)
print(end-start)

[1, 4, 9, 16, 25, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16]
0.0


In [3]:
arr1=np.array([1,2,3,4,5,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4])
start=time.time()
result=arr1**2
end=time.time()
print(result)
print(end-start)

[ 1  4  9 16 25 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16
 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16
 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16]
0.0


**broadcasting** it means performing a operation with a scalar on the whole array withour using extra space (ex . adding an element in an array ).
It basically streches the smaller data to fit in the bigger one and broadcasts it into bigger one 


In [8]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [9]:
a+[10]

array([11, 12, 13, 14, 15])

In [10]:
# 1D array addittion (broadcasting)
arr1=np.array([1,2,3,4,5])
arr2=np.array([1,2,3,4,5])
arr1+arr2

array([ 2,  4,  6,  8, 10])

In [11]:
# 2D addition (broadcasting)
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([10,20,30])
arr1+arr2

array([[11, 22, 33],
       [14, 25, 36]])