In [4]:
import numpy as np


In [5]:

a= np.array ([[1,2,3],[6,5,4],[7,8,9]])


In [6]:
flat=a.flatten()

In [7]:
flat


array([1, 2, 3, 6, 5, 4, 7, 8, 9])

In [8]:
flat[2:]

array([3, 6, 5, 4, 7, 8, 9])

In [9]:
flat[:5]

array([1, 2, 3, 6, 5])

In [10]:
flat[:]

array([1, 2, 3, 6, 5, 4, 7, 8, 9])

In [11]:
# [start:end:gap]
flat[::2]

array([1, 3, 5, 7, 9])

In [12]:
flat[2:7:2]

array([3, 5, 7])

**note:** In numpyslicing gives a view not a copy so If we make changes in the slice it will reflect the original array 
to overcome from this we use .copy() method 

In [14]:
b=flat[2:7]


In [15]:
b

array([3, 6, 5, 4, 7])

In [16]:
b[1]

np.int64(6)

In [17]:
b[1]=300
flat

array([  1,   2,   3, 300,   5,   4,   7,   8,   9])

In [18]:
b=flat[2:7].copy()

In [19]:
b[1]=1000
flat

array([  1,   2,   3, 300,   5,   4,   7,   8,   9])

In [21]:
# fancy indexing arr[[index,index...]]
flat[[2,3,5]]

array([  3, 300,   4])

In [22]:
# boolean masking arr[condition]
flat[flat>5]

array([300,   7,   8,   9])

**exercise practice**


In [23]:
arr=np.array([1,2,3,4,5,6,7,8,9])

In [24]:
matrix=np.array([[arr[:3]],[arr[3:6]],[arr[6:]]])

In [25]:
matrix

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

In [26]:
arr2=np.array([1.1,2.2,3.3])

In [27]:
arr2=[int(x) for x in arr2]

In [28]:
arr2

[1, 2, 3]