In [1]:
import numpy as np

In [8]:
arr=np.array([1,4,2,88,19,12,0])
arr.astype("int32")

array([ 1,  4,  2, 88, 19, 12,  0], dtype=int32)

In [29]:
arr2=np.array([1,23,90,5,23,5,6])
arr2.astype("int32")

array([ 1, 23, 90,  5, 23,  5,  6], dtype=int32)

In [9]:
arr.max()

np.int64(88)

In [10]:
print(arr.min())

0


In [11]:
arr.argmax()

np.int64(3)

In [12]:
arr.argmin()

np.int64(6)

In [13]:
arr.sum()

np.int64(126)

In [15]:
arr.prod()

np.int64(0)

In [23]:
np.median(arr)

np.float64(4.0)

In [16]:
np.mean(arr)

np.float64(18.0)

In [17]:
np.std(arr)

np.float64(29.281881282263466)

In [18]:
np.var(arr)

np.float64(857.4285714285714)

In [19]:
np.percentile(arr,19)

np.float64(1.1400000000000001)

In [20]:
np.percentile(arr,5)

np.float64(0.30000000000000004)

In [24]:
np.log(arr)

C:\Users\ABHISHEK\AppData\Local\Temp\ipykernel_25188\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([0.        , 1.38629436, 0.69314718, 4.47733681, 2.94443898,
       2.48490665,       -inf])

In [26]:
np.exp(arr)

array([2.71828183e+00, 5.45981500e+01, 7.38905610e+00, 1.65163625e+38,
       1.78482301e+08, 1.62754791e+05, 1.00000000e+00])

In [27]:
np.cumsum(arr)

array([  1,   5,   7,  95, 114, 126, 126])

In [28]:
np.diff(arr)

array([  3,  -2,  86, -69,  -7, -12])

In [30]:
np.unique(arr2)

array([ 1,  5,  6, 23, 90])

In [31]:
np.corrcoef(arr,arr2)

array([[ 1.        , -0.25944288],
       [-0.25944288,  1.        ]])