In [1]:
import numpy as np


**2D array**


In [9]:
arr=np.array([[1,2,3],[3,5,6],[1,4,6]])
arr

array([[1, 2, 3],
       [3, 5, 6],
       [1, 4, 6]])

In [7]:
# in 2 d array axis =0 -> row and axis=1 -> col
np.sum(arr,axis=0)

array([ 5, 11, 15])

In [8]:
np.sum(arr,axis=1)

array([ 6, 14, 11])

In [10]:
arr[2,1]

np.int64(4)

In [11]:
arr[0:1,1:3]

array([[2, 3]])

**3D array**

In [12]:
arr=np.array([[[1,2,3],[4,5,6]],[[11,22,33],[44,55,66]],[[12,13,14],[15,16,17]]])

In [13]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 22, 33],
        [44, 55, 66]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [14]:
arr[0,1,1]

np.int64(5)

In [15]:
arr[1:,0:2,:2]

array([[[11, 22],
        [44, 55]],

       [[12, 13],
        [15, 16]]])