In [1]:
import numpy as np


In [10]:
data=np.array([[10,20,30],[1,2,3],[32,41,50],[12,15,25]])

In [11]:
mean=np.mean(data,axis=0)
mean

array([13.75, 19.5 , 27.  ])

In [12]:
std=np.std(data,axis=0)
std

array([11.32199187, 14.04457191, 16.7182535 ])

In [13]:
normalized_data=(data-mean)/std
normalized_data

array([[-0.3312138 ,  0.03560094,  0.17944458],
       [-1.12612693, -1.246033  , -1.43555665],
       [ 1.61190718,  1.53084054,  1.37574179],
       [-0.15456644, -0.32040848, -0.11962972]])