In [2]:
import numpy as np

In [4]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [7]:
np.array([1,2,3,"abhi","shek"])

array(['1', '2', '3', 'abhi', 'shek'], dtype='<U21')

In [12]:
arr=np.array([[1,2,3],[4,5,6]])

In [13]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
type(arr)

numpy.ndarray

In [17]:
arr.shape

(2, 3)

In [4]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [7]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
np.zeros((4,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
np.full(4,3)

array([3, 3, 3, 3])

In [10]:
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [13]:
np.arange(3,200,5)

array([  3,   8,  13,  18,  23,  28,  33,  38,  43,  48,  53,  58,  63,
        68,  73,  78,  83,  88,  93,  98, 103, 108, 113, 118, 123, 128,
       133, 138, 143, 148, 153, 158, 163, 168, 173, 178, 183, 188, 193,
       198])

In [15]:
s=np.arange(0,171,17)

In [17]:
s

array([  0,  17,  34,  51,  68,  85, 102, 119, 136, 153, 170])

In [19]:
# equally spreading the space between 1 and 100 in 7 parts
np.linspace(1,100,7)

array([  1. ,  17.5,  34. ,  50.5,  67. ,  83.5, 100. ])

In [20]:
myarr=np.array([[1,2,3],[5,3,1],[1,2,3],[4,3,0]])

In [21]:
myarr.size

12

In [22]:
myarr.shape

(4, 3)

In [23]:
# dimension of array
myarr.ndim

2

In [24]:
myarr.dtype

dtype('int64')

In [28]:
# forcefully changing datatype
n=myarr.astype('float32')

In [29]:
n.dtype


dtype('float32')

In [30]:
myarr.dtype

dtype('int64')

In [34]:
# reshaping the array from 4*3 to 6*2
reshapedArr=myarr.reshape(6,2)

In [35]:
reshapedArr

array([[1, 2],
       [3, 5],
       [3, 1],
       [1, 2],
       [3, 4],
       [3, 0]])

In [33]:
myarr

array([[1, 2, 3],
       [5, 3, 1],
       [1, 2, 3],
       [4, 3, 0]])

In [37]:
# flatening the 2d array into a 1d linear array
flatArr=myarr.flatten()
flatArr

array([1, 2, 3, 5, 3, 1, 1, 2, 3, 4, 3, 0])